### PR TITLE
add maybe::pair

### PR DESCRIPTION
**Pull request by dadleyy**
👋 @hojberg 😄 !! Just putting this here; I've found it helpful in some of my use of `seidr` so I figured I'd just see if it's worth adding proper.

Adding the ability to combine two `Maybe`s into a single `Maybe` with the contents of the two placed into a tuple. This is inspired by rust's [`Option::zip`](https://doc.rust-lang.org/std/option/enum.Option.html#method.zip) (which maybe should be the name here too?).

### CODE REVIEW

**Comment by hojberg** [comment]
@dadleyy cool!!!

Hmm I think the naming should be `zip` or `pair`:

  Haskell similar naming (with Vector, not Maybe)
  https://hoogle.haskell.org/?hoogle=Maybe%20a%20-%3E%20Maybe%20b%20-%3E%20Maybe%20(a%2C%20b)
  
  Elm:
  https://klaftertief.github.io/elm-search/?q=Maybe%20a%20-%3E%20Maybe%20b%20-%3E%20Maybe%20(a%2C%20b)

  I think I like `pair` - what you do you think?

Sidenote, this also seems related to [`Maybe.map2`](https://package.elm-lang.org/packages/elm/core/latest/Maybe#map2) — perhaps we should add that method and create this one out of that?

**Comment by dadleyy** [comment]
> Sidenote, this also seems related to Maybe.map2 — perhaps we should add that method and create this one out of that?

good call; I updated and went with `mapWith`, what do you think?

**Comment by hojberg** [comment]
@dadleyy looks like there's a conflict after I updated the target to `main`.

What do you think about sticking with `map2`? I agree that `mapWith` is a better name, but `map2` (`map3` and so on), seems to be established conventions. 🤷‍♂️ 

This otherwise is looking good to me 🎉

**Comment by dadleyy** [comment]
@hojberg your lib, your rules 😄 , updated

side note - it doesn't look like the github actions are running on my fork, but running `npm test` locally gives me an eslint error about a missing return type on [`List::empty`](https://github.com/hojberg/seidr/blob/ae363606304aed1939d1faba36d564941ba73b5e/src/list.ts#L10), do you want me to fix that here while I'm in here or do it separately?

**Comment by hojberg** [comment]
If you don't mind that would be awesome 🙏

**Comment by hojberg** [comment]
Thank you!! 😄

**Pull request merged**
